<!DOCTYPE html>
<html>
<body>

<p>My  personal list of her favorite video game series </p>
<img src='<?php echo $block->getUrl("https://github.com/VColeman-games/PHPDemo/blob/db70dbdf0767e3e2b32f896fc4aab188113a4261/Assignment%201/")?>assassin_s_creed_syndicate_pc.jpg'>
<p>Assassin's Creed is a popular video game series by Ubisoft.It is about a group called the Assassins as they take out the  corruption in their various towns and cities. The game takes place in various historical time periods. I love this game because it promotes rebelling against corruptted power and overthrowing dictators. </p>
<img src='https://github.com/VColeman-games/PHPDemo/blob/431f8349956d3954a4ddfb9777be66914e1f48e6/Assignment%201/assassin_s_creed_syndicate_pc.jpg'>
<p>The Mafia series is a series created by 2K. Each game is about the main character getting involved with the mafia and how their live changed after joining. I enjoy this game for it's amazing storytelling.   </p>
<img src='https://github.com/VColeman-games/PHPDemo/blob/431f8349956d3954a4ddfb9777be66914e1f48e6/Assignment%201/assassin_s_creed_syndicate_pc.jpg' ">
<p>Borderlands is a first-person shooter role-playing game created by 2k. The game is about a group of vault hunter finding treasure on various planets. I enjoy this game because of it's fast pace gameplay. </p>
</body>
</html>